# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/44444444-4444-4444-8888-888888888888";
      fsType = "ext4";
    };

    "/ssd" = {
      device = "/dev/disk/by-uuid/12f6e6d2-6b5c-4a26-99ca-566eaad9da01";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
      ];
    };
    "/backups" = {
      device = "/dev/disk/by-uuid/8aa46536-1eb9-442f-84d2-2ce4be54feb7";
      fsType = "ext4";
      options = [
        "defaults"
        "nofail"
      ];
    };
    "/var/lib/nextcloud" = {
      device = "/ssd/nextcloud_data";
      fsType = "none"; # bc it's not a real filesystem
      options = [ "bind" ];
    };
    "/var/lib/karakeep" = {
      device = "/ssd/karakeep_data";
      fsType = "none"; # bc it's not a real filesystem
      options = [ "bind" ];
    };
  };

  swapDevices = [
    {
      device = "/ssd/swapfile";
      size = 16 * 1024;
    }
  ];
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
